### ISSUE TITLE
createJob should accept arbitrary job params

### ISSUE THREAD

**Issue by TomKaltz** [grantcarthew/node-rethinkdb-job-queue#11]
Seems that the following does not work....
```
let jobOptions = {
  retryDelay:500,
  retryMax:10,
  timeout:60000,
  someParam:'job data'
}
let job = queue.createJob(jobOptions)
```
the resulting job object does not contain ```someParam```.

**Comment by grantcarthew** [comment]
That's by design @TomKaltz.
`Queue.createJob` returns an object with the basic job schema. You then add data to the job any way you like.

```js

let job = q.createJob({
  retryDelay:500,
  retryMax:10,
  timeout:60000
})
job.anything = 'something'

```
The job options are just that, options for how the job runs.
I don't think I want to change that.

**Comment by TomKaltz** [comment]
IMHO it seems messy but I really do think createJob is unneeded.  Regarding #9, addJob() should be able to accept an object like...
```
{
  retryDelay:500,
  retryMax:10,
  timeout:60000,
  someParam:'job data',
  someOtherParam:'more job data'
}
```
...and just add the job

or if you'd like to keep job options separate then maybe it should be...

```
addJob(jobDataParams,jobOptions)
```

**Comment by grantcarthew** [comment]
One of the reasons I kept `Queue.createJob()` as a separate method is for creating bulk jobs. Lets say I have 10k jobs to create. If I add them to the queue using `Queue.addJob()` it will cause 10k round trips to the database.

By using `Queue.createJob()` you can create 10k jobs, populate  the job data, then add 10k jobs to the database in one round trip.

**Comment by grantcarthew** [comment]
I was just thinking about this and looking at the docs.
Forgot that I had written this.
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue.addJob#why-separate-queuecreatejob-and-queueaddjob

**Comment by grantcarthew** [comment]
This choice will affect #9 also.
By having `Queue.addJob` accept a string or object it will cause many writes to the database if a user of the module is adding many jobs.

**Comment by grantcarthew** [comment]
I decided not to change this API @TomKaltz.
I know it is not the cleanest API to ever exist however there are advantages.

### Pros

*   Can create jobs synchronously.
*   No database access until added to the queue.
*   Custom properties make the jobs very flexible.

### Cons

*   API is a little messy

I did consider an extra Queue method to create and add however it is moving away from keeping it simple again.

I might make minor changes to the API but the `createJob` and `addJob` will be separate. 

Thanks again.

**Comment by grantcarthew** [comment]
Hi again @TomKaltz,

I deleted a few comments to cleanup this Issue.

I have been thinking about your suggestions and think I might have a good solution for this API.

I am thinking about removing the options from `Queue.createJob(options)` and adding in some functions on the `Job` objects to enable fluent API.

Something like this.

```js

const q = new Queue()
q.jobOptions = { // Set job default options here }

// Will only need to change the options if you are not happy with the above defaults.
let job = q.createJob({  'job data here will be Object.assigned' }).timeout(123).pritorty('high')

// Can always change options here
job.retryMax = 5

// Will be keeping addJob separate
q.addJob(job)

```

What are your thoughts?

**Comment by grantcarthew** [comment]
Hey @TomKaltz, I decided to run with your idea here. v0.4.0 now supports passing values or objects and will update properties. I also added in a fluent api for jobs so you can do the following.

```js

let job = q.createJob({ path: '/some/file.mkv', priority: 'high' }).setTimeout(1234).setRetryMax(4)

```
I had to put `set` in front of the method names to prevent conflicts with the property names.

Thanks again.
