### ISSUE TITLE
Error stack trace in log entry

### ISSUE THREAD

**Issue by TomKaltz** [grantcarthew/node-rethinkdb-job-queue#12]
Is there a way to have stack traces logged inside the database when the job fails with Error?

**Comment by grantcarthew** [comment]
Sure, just here I could put in the stack trace.
https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/ba7c971d8c5626005b74ea417138e2c27b17819a/src/job-failed.js#L28

Keep the improvements coming mate.

What project are you using this on?

**Comment by TomKaltz** [comment]
My project is automated video converting and uploading to Vimeo.  About to put this thing in production.  I will let you know how it goes. Been a pleasure taking this thing for a "spin".  Great docs!

**Comment by grantcarthew** [comment]
Hi @TomKaltz, Just published v0.3.0.
Added the stack and error messages to the log when `next(err)` is called.

Thanks again for your input.
