### ISSUE TITLE
processing a job and setting it as pending

### ISSUE THREAD

**Issue by marcoalbarelli** [grantcarthew/node-rethinkdb-job-queue#16]
Hi 
I need to process a job in two separate and independent steps
In the `process` method I get the job, I fire up a detached process that may end in a remote system calling an API on my server, which in turn would retrieve the job and set it as completed/failed/whatever
At this point the `process` method should exit in a peaceful way, possibly setting the job in a `pending` state
Too bad the `next` callback only sets the job as completed, which is not the case in my scenario

Am I getting things wrong or isn't there a real way to obtain this yet?
If so I'd be happy to provide a PR

**Comment by alexgorbatchev** [comment]
Have you thought about splitting this into multiple jobs? 

Alternatively if you `process.exit()` from the first process, you can try `Queue.findJob` in the spawned process and mark it complete there.

https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue.findJob

**Comment by marcoalbarelli** [comment]
Thanks for the answer
I'm not sure I get your suggestion about splitting
If I'm not mistaken you're suggesting to have two queues, one for outbound messages (Q1) and one for inbound message (Q2)
This way when I receive one job (J1) that spawns a request I create a new job (J2) in the `inbound` queue and then mark the job (J1) as done (calling `next()` in the process method) 

This way when on a separate process I receive a message I can check if there is a job with a specified value (the message will carry on my values by design)

All in all seems like a nice solution
Thx :)
