### ISSUE TITLE
Remove the `Job.createLog` method.

### ISSUE THREAD

**Issue by grantcarthew** [grantcarthew/node-rethinkdb-job-queue#23]
It seems a little redundant.

The `Queue.createJob` and `Queue.addJob` are designed as separate processes to enable bulk local creation of jobs.

It is unlikely that you would ever need to create bulk job logs.

**Comment by TomKaltz** [comment]
Yes I totally agree. Less boilerplate the better. Simple streamlined API is best!

**Comment by grantcarthew** [comment]
Removed in v0.5.0
