### ISSUE TITLE
Update the `Job.addLog` signature

### ISSUE THREAD

**Issue by grantcarthew** [grantcarthew/node-rethinkdb-job-queue#24]
Due to #23, the `Job.addLog` api needs to improve.

**Comment by marcoalbarelli** [comment]
If you lay down some specifications I may be able to help and make a PR
It looks like I'll be using this queue lib for a project notwithstanding the "closing" of rethinkdb

**Comment by grantcarthew** [comment]
Updated in v0.5.0
