### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by marcoalbarelli** [grantcarthew/node-rethinkdb-job-queue#25]
After our discussion in #17 I'd like to add a couple of sentences on the documentation, mostly regarding the `next` method implicit behaviour and how to manage multiple-step jobs
I never contributed to github's wikis
Shall I make a PR? If so, where from?

**Comment by grantcarthew** [comment]
I think you can just edit them as the PR. Have a look a the top of the page.

**Comment by grantcarthew** [comment]
I will be updating some documentation tomorrow @marcoalbarelli.
May add a `Job Logging` page and a `Job Processing` page. Move some of the `Queue.process` content to a descriptive document.

**Comment by marcoalbarelli** [comment]
Sure, I'll try to make time today

Il 9 ottobre 2016 11:05:57 CEST, Grant Carthew <notifications@github.com> ha scritto:
>I will be updating some documentation tomorrow @marcoalbarelli.
>May add a `Job Logging` page and a `Job Processing` page. Move some of
>the `Queue.process` content to a descriptive document.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/grantcarthew/node-rethinkdb-job-queue/issues/25#issuecomment-252474338

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by grantcarthew** [comment]
Hi @marcoalbarelli, I have been working on the documentation to fix up changes made to the API.
I also added two new documents.

Fixed up pages:
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Job.addLog
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Job.update

New documents:
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Job-Processing
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Job-Logging

Have a read and let me know if that helps.

**Comment by marcoalbarelli** [comment]
I think the changes are good: there's just one thing I find a little misleading:
In the `jobUpdate` page you reference the `data` property of both the job itself and the log entry
This highlights a basic grey area: Shall the user use the property of the job or of the log entries?

The `update` method name is misleading because what it actually do is two things: 
Save any new properties one may have updated/changed in the Job entity *and* create a log entry with some data passed via arguments (basically a redundant version of `addLog`)

Regarding the `process` description, I think a proper explanation of how to manage multistep processing is still missing, maybe I should add something to the tutorial and just link it in that page.
I'll try to find the time to propose thise changes to you.

Still haven't looked into changing wiki pages on GH, but I think it won't be difficult

**Comment by grantcarthew** [comment]
I see what you are getting at with regards to the `update` method. There needs to be a log added to the job if you update it for some reason, that's why I added the log arguments. It isn't redundant. If someone made four updates to a job it needs to be logged. The `job.someData` could change from value1 to value2 to value3 and back to value1. If there isn't some record of these changes it would be hard to fault find or track job issues.

I could remove the users options for the update log entry and just get a complete copy of the old job prior to the update and log that.

With regards to processing complex tasks with multiple jobs, maybe an FAQ page would be a better option.

**Comment by grantcarthew** [comment]
I just change the `Job.update` api @marcoalbarelli. Reverted it back to simply `Job.update()`. It now adds a log entry internally with a copy of the old job from the database as the log data.

I have bumped `rethinkdb-job-queue` to v1.0.0 also to lock the API.

**Comment by grantcarthew** [comment]
I have added a FAQ document here:
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/FAQ

It is referenced at the bottom of the Job Processing document.

I'm happy with this detail however if you want to add to it @marcoalbarelli, feel free.

I think this project is stable, hence the bump to v1.0.0. Moving to maintenance mode and fixing bugs as they arise.

**Comment by grantcarthew** [comment]
I'm going to close this for now @marcoalbarelli. Feel free to open it again if you want to discuss it further.

Thanks a heap for your input.
