### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by alexgorbatchev** [grantcarthew/node-rethinkdb-job-queue#3]
Thanks a ton for this module, great effort and documentation. I have a few suggestions:

* Normalize all "time" values in milliseconds, I found it really strange to have to deal with seconds and especially days.
* Don't require `rethinkdbdash`. IMO it's best for libraries to just take in the connection object and let it up to the user to configure it and make sure it's open. Less work for you, more flexibility for everyone else.
* Don't use `bluebird`. I looked at every single usage of `Promise` in the code and you are using only standard APIs that are now part of node.
* Replace `moment` with helper methods. I saw only `add` method being using, the rest of the library is completely unused.

**Comment by grantcarthew** [comment]
Hi @alexgorbatchev and thanks for the feedback.

*   Normalize time - I see no reason not to change to ms. I was just making the module easier to use by using seconds and days. Job timeout values and the like would rarely be less than a second.

*   `rethinkdbdash` - I never though about asking the consumer for the connection. This would work I suppose. I took most of my inspiration from the other Queue packages on NPM.

*   `bluebird` - I am using some of the features of `bluebird`. Specifically [props](http://bluebirdjs.com/docs/api/promise.props.html) and [delay](http://bluebirdjs.com/docs/api/delay.html). I'm only using delay in tests though. I tend to like `bluebird` and am not keen to replace it. [Read here](http://panthersoftware.com/2016/05/18/native-vs-third-party-promises/).

*   `moment` - I was already thinking I didn't need a date management package. As you can see on the [Delayed Job](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Delayed-Job) document. 

I'm going to ask on the [RethinkDB Slack General Channel](https://rethinkdb.slack.com/messages/general/) to see if I can get more feedback on this.

**Comment by ha1331** [comment]
can't say if you should ditch bluebird or not, but the native implementation seems to be slower than bluebird, if that makes a difference in this instance

source:  http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird

**Comment by alexgorbatchev** [comment]
Thank you for detailed response. In terms of providing connecting to the module, it's always a struggle when a library creates own connection. A production system generally has special cases of managing connect/disconnect/reconnect events, supplemented with logging and other things.

I'm very surprised to hear that native is slower than bluebird... I just ran the tests myself and it seems that native is about 4 times slower.

**Comment by ha1331** [comment]
maybe there should be an option of either getting a connection or creating it's own. Wouldn't that fit most usecases?

**Comment by grantcarthew** [comment]
Hi @ha1331 and thanks for the feedback.

After a day of reflection and research I have decided to take two of your suggestions @alexgorbatchev. I have already started changing the instantiation api to support a connection object or options.

Once the changes are complete you will be able to do something like this.

```js

const conOptions = {
  host: 'localhost',
  port: 28015,
  db: 'Queue'
}

const q = new Queue(options, conOptions)

```

Or this.

```js

const con = rethinkdb({host: 'localhost', port: 28015, db: 'Queue'})

const q = new Queue(options, con)

```

I haven't finished it yet so this is just to give you an idea.

The other suggestion I will take on board is the change to milliseconds. I will make changes after the current work unless you want to contribute.

With respect to `bluebird` and `moment` I will keep these libraries.

I looked at changing code to remove `moment` however it doesn't make sense to not use it. `moment` is well supported and well documented and I would just be repeating the work already done by that project.

`bluebird` is just awesome.

Thank you very much for the suggestion @alexgorbatchev.

**Comment by alexgorbatchev** [comment]
Fair points, thank you so much for your hard work!

**Comment by grantcarthew** [comment]
Hey @alexgorbatchev. After changing the code to use milliseconds for all options is was not a big jump to remove `moment`.  I just published a new version that has three of your suggestions applied. I kept `bluebird`.

I'll close this now. Thanks again.

**Comment by alexgorbatchev** [comment]
amazing work, thank you! 👍
