### ISSUE TITLE
Support for parallelism

### ISSUE THREAD

**Issue by sagivf** [grantcarthew/node-rethinkdb-job-queue#35]
Can this be parallelised between processes?

For example if I create a queue on two processes with the same `cxnOptions` and `qOptions` and add jobs via both - will `Queue.findJob` return the same results for both?

**Comment by grantcarthew** [comment]
Yes. The `Queue.name` defines the name of the database table. `Queue.findJob` queries the database table. If you have many Queue objects with the same DB and Name config, they will all be pointing at the same database and table.

**Comment by sagivf** [comment]
Thanks @grantcarthew, that's great.
Just to be clear - Is there any caching done on the process level? I mean are there any edge cases where an operation might go directly to the DB but use locally stored data?
Have you tried running Jobs on multiple processed?

**Comment by grantcarthew** [comment]
No cache at all. Every job process/query is atomic to the database.

The `queue-process.spec` test file does a multi-process test.

**Comment by TomKaltz** [comment]
Just for further clarification...if I have job a processor/worker on two separate machines processing jobs for the same queue, a single queued job will only be processed on **one** of the workers, correct?

**Comment by grantcarthew** [comment]
Yes @TomKaltz. The job status gets changed from `waiting` to `active` when it is retrieved from the database. This is an atomic operation. The internal function `getNextJob()` will only retrieve jobs that have a `waiting` or `failed` status etc.
