### ISSUE TITLE
enable coverage reports with istanbul

### ISSUE THREAD

**Issue by thomasmodeneis** [grantcarthew/node-rethinkdb-job-queue#40]
Hi,

I just happen to see that we don't have any coverage report, so I took the initiative to study and implement one.

I'm just not sure if we should put the generate coverage report with the project or not.
This will be your call, I will be committing only the coverage for now without reports.

**Comment by thomasmodeneis** [comment]
Just that the commit went in the same pull request that was already opened, that was unfortunate git failure :|

But you can checkout that and see, I bet you will like it.
Cheers.

**Comment by grantcarthew** [comment]
I don't have time to checkout the coverage yet @thomasmodeneis. Will do when I can.

**Comment by grantcarthew** [comment]
Thanks @thomasmodeneis
