### ISSUE TITLE
require(...) is not a function

### ISSUE THREAD

**Issue by chrisabrams** [grantcarthew/node-rethinkdb-job-queue#42]
This [line](https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/9d9c19f5cebf197014e4bcee88bdaa592c5e7f3c/src/enums.js#L1) is erroring for me :/

```
TypeError: require(...) is not a function
    at Object.<anonymous> (node_modules/rethinkdb-job-queue/dist/enums.js:3:33)
```

If I change the line to: `var logger = require('debug')('')` the library loads fine.

I am on Node.js `6.9.1`.

**Comment by grantcarthew** [comment]
Thanks @chrisabrams. There was a circular dependency: enums required logger which required datetime which required enums.....   oops.

Interesting it didn't show up on my system.

v2.0.2 published. Thanks again.
