### ISSUE TITLE
Consider accepting an existing rethinkdbdash connection

### ISSUE THREAD

**Issue by chrisabrams** [grantcarthew/node-rethinkdb-job-queue#44]
I'm working on a larger project which is trying to retain a single connection pool. Throughout the project I create many jobs using this wonderful library. I'd like to request the option to pass `r` to the job to utilize an existing connection pool, rather than making another.

I've considered replacing `q.r` but thought there might be a  more elegant way of handling this?

**Comment by grantcarthew** [comment]
That was done in v1 Chris. Read the top of this page:
https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Connection

@chrisabrams

**Comment by chrisabrams** [comment]
@grantcarthew oh I get it now; you can pass `r` as the options to the queue itself. That is great news :) Thanks!
