### ISSUE TITLE
Possible to use ReQL transformations with Queue.findJob?

### ISSUE THREAD

**Issue by shawnhwei** [grantcarthew/node-rethinkdb-job-queue#46]
Title.

**Comment by grantcarthew** [comment]
Hi @shawnhwei,

In its current state, the options to `Queue.findJob` are passed into the ReQL filter.
Ref: https://www.rethinkdb.com/api/javascript/filter/

So anything you can pass to the filter is possible.

If you pass in a predicate function you would be able to use the transformations within the function.

Try it out mate.

Grant.

**Comment by shawnhwei** [comment]
@grantcarthew I'm not terribly experienced with ReQL but I thought the predicate function was used to simply determine whether each individual record is accepted or rejected by the filter?

I'd specifically like to use the orderBy and limit functions which seem to be applied to sequences/arrays. I saw the raw option for the returned data, can ReQL functions be chained onto a raw result?

Thanks!

**Comment by grantcarthew** [comment]
Ah, well that's not what `Queue.findJob` is for. Raw simply returns the raw database result, not ReQL objects.

In my opinion, this is where you could simply use the `rethinkdbdash` driver directly to interact with the jobs.

The `rethinkdbdash` driver is publicly exposed on the Queue object by using `Queue.r`.
Ref: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue.r

The Job schema is not going to change any time soon so I see nothing wrong with accessing the Table directly and searching using any of the `ReQL` features.

Be aware, changing the status of a job may prevent it from being processed. Same with some of the other properties of a Job. Have a close read of the [Job Schema](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Job-Schema) and the rest of the documentation if you want to change a property value outside of the Queue objects.

**Comment by shawnhwei** [comment]
I see. Thanks!
