### ISSUE TITLE
RethinkDB Joins the Linux Foundation!

### ISSUE THREAD

**Issue by grantcarthew** [grantcarthew/node-rethinkdb-job-queue#50]
https://rethinkdb.com/blog/rethinkdb-joins-linux-foundation/

This is great news. I have private projects invested in RethinkDB outside of this job queue as many of you probably do. All uncertainty has been removed and we can start moving forward.

With RethinkDBs move to the Linux Foundation on an ASLv2 license, the sky is clear!

**Comment by thomasmodeneis** [comment]
Great news @grantcarthew :D
Thanks for the update!

**Comment by chrisabrams** [comment]
@grantcarthew does this mean you are going to be bringing some of those projects to light?

**Comment by grantcarthew** [comment]
Ha, as usual, if I get the time!

It will be invite only though.

**Comment by marcoalbarelli** [comment]
I agree, this is great news not just for this good queue
