### ISSUE TITLE
What does "state":  "reviewed" mean?

### ISSUE THREAD

**Issue by chrisabrams** [grantcarthew/node-rethinkdb-job-queue#52]
I can't seem to find what `"state":  "reviewed"` means in the docs. I currently have a job sitting in the db under this state.

On [this](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Job-Status) document page, there is no mention of "reviewed"

**Comment by grantcarthew** [comment]
Hi Chris, have a look at this: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/State-Document

**Comment by chrisabrams** [comment]
Ah ha, thx!
