### ISSUE TITLE
TypeScript Type Definitions *.d.ts

### ISSUE THREAD

**Issue by bchavez** [grantcarthew/node-rethinkdb-job-queue#53]
Hi there,

Great work on this really neat job queue for RethinkDB! I was wondering if it was possible to also [distribute TypeScript ambient type definitions](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) for your API? If so, I'd really like to use **TypeScript** with your project.

Currently, I maintain the C# RethinkDB driver and was thinking about porting your project to C# since I don't normally write server-side node stuff; but I thought I'd ask before I tried anything.

Many thanks,
Brian

**Comment by grantcarthew** [comment]
Hey Brian @bchavez,

I don't know how you would go writing this in C#. You could take ideas from it for sure.

There is a lot of doucmentation. Have a read though it and you will appreciate the issues I came across.

You can learn a lot from the [queue-process.js](https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/queue-process.js) file.

With regards to .d.ts files. I don't know much about them. If you want to contribute them here or where ever they need to go I am happy to add them.

Also happy to help where I can. I spent 10 years working with C#. Don't do much with it now.

**Comment by grantcarthew** [comment]
Any feedback @bchavez ?

**Comment by bchavez** [comment]
Hi @grantcarthew ,

Thank you for your help and guidance in where to start.

I'm not sure what I'm going to do yet. My feeling is I'll probably work on porting it to C# because there aren't any TypeScript bindings for the JavaScript driver. :( There was some talk in Slack about writing a TypeScript driver to replace the official JavaScript/coffeescript driver. So, I don't know. Not sure I have enough time to develop *yet another* driver for RethinkDB (in TypeScript). :)

For sure, I'll send you a PR if things change. :+1:

**Comment by viridia** [comment]
BTW here's my attempt to create a type definitions file for this. Not complete, but seems to be working so far...

```
// Type definitions for rethinkdb-job-queue
// Project: https://github.com/grantcarthew/node-rethinkdb-job-queue
import { EventEmitter } from 'events';

interface PredicateFunction<P> {
  (job: P): boolean;
}

interface ProcessCallback<P> {
  (job: P,
   next: (error?: Error, jobResult?: P | string) => void,
   onCancel: (job: P, cancellationCallback?: () => void) => void): void;
}

declare class Queue<P extends Queue.Job> extends EventEmitter {
  public readonly name: string;
  public readonly id: string;
  public readonly host: string;
  public readonly port: number;
  public readonly db: string;
  //  get r () { return this._r } // What type is this?
  public readonly changeFeed: boolean;
  public readonly master: boolean;
  public readonly masterInterval: boolean | number;
  public jobOptions: Queue.JobOptions;
  public readonly  removeFinishedJobs: boolean | number;
  public readonly running: number;
  public concurrency: number;
  public readonly paused: boolean;
  public readonly idle: boolean;
  constructor(cxOptions?: Queue.ConnectionOptions, qOptions?: Queue.QueueOptions);
  public addJob(job: P | P[]): Promise<P[]>;
  public createJob(jobData?: object): P;
  public cancelJob(job: string | P | P[]): Promise<P[]>;
  public findJob(predicate: Object | PredicateFunction<P>, raw?: boolean): Promise<P[]>;
  public getJob(job: string | P | P[]): Promise<P[]>;
  public process(handler: ProcessCallback<P>): Promise<boolean>;
  public removeJob(job: string | P | P[]): Promise<P[]>;
}

declare namespace Queue {
  interface ConnectionOptions {
    host?: string;
    port?: number;
    db?: string;
  }

  interface QueueOptions {
    name?: string;
    databaseInitDelay?: number;
    queryRunOptions?: boolean;
    changeFeed?: boolean;
    concurrency?: number;
    masterInterval?: number;
    limitJobLogs?: number;
    removeFinishedJobs?: number | boolean;
  }

  enum Priority {
    lowest,
    low,
    normal,
    medium,
    high,
    highest,
  }

  interface JobOptions {
    name?: string;
    priority?: Priority;
    timeout?: number;
    retryDelay?: number;
    retryMax?: number;
    repeat?: boolean | number;
    repeatDelay?: number;
    dateEnable?: Date;
  }

  export interface Job {
    id?: string;
    name?: string;
    priority?: Priority;
    timeout?: number;
    retryDelay?: number;
    retryMax?: number;
    retryCount?: number;
    repeat?: boolean | number;
    repeatDelay?: number;
    processCount?: number;
    progress?: number;
    status?: string;
    log?: LogEntry[];
    dateCreated?: Date;
    dateStarted?: Date;
    dateFinished?: Date;
    queueId?: string;
  }

  /** Standard implementation of Job. Fields are filled in when the job is added. */
  export class AbstractJob {
    public id?: string;
    public name?: string;
    public priority?: Queue.Priority;
    public timeout?: number;
    public retryDelay?: number;
    public retryMax?: number;
    public retryCount?: number;
    public repeat?: boolean | number;
    public repeatDelay?: number;
    public processCount?: number;
    public progress?: number;
    public status?: string;
    public log?: Queue.LogEntry[];
    public dateCreated?: Date;
    public dateStarted?: Date;
    public dateFinished?: Date;
    public queueId?: string;
  }

  export interface LogEntry {
    date: Date;
    message?: string;
    queueId: string;
    status?: string;
    type?: string;
    data?: Object;
    // retryCount
  }
}

export = Queue;
```

Notes:

* 'Queue' is both a class and a namespace, so you can say `new Queue` as well as `Queue.Job`.
* Since applications can extend the Job type, I made the Queue a generic where the type argument extends Job.
* `AbstractJob` is intended as a base class for applications wanting to implement the Job interface.

**Comment by grantcarthew** [comment]
Hi @viridia 

Can you send a PR for this? is it worth putting in the project?

**Comment by viridia** [comment]
It's not quite done, but when it is I can certainly send a PR. I think if you put it in the same directory as the index.js file everything will just work.

Alternatively, if you don't care too much about TypeScript, I can upload it to npm as a separate package in the @types namespace as @types/rethinkdb-job-queue. It means that typescript users will have to install an additional package, but they are used to doing that with other npm packages.

**Comment by grantcarthew** [comment]
I'm happy to have it in the project @viridia

**Comment by viridia** [comment]
Continuing to work on this, but I want to test it some more before I make a PR. I'm now starting to wish there were typescript bindings for RethinkDbDash (there's one package but it appears to be abandonware.)

Note that I'm relatively new to TypeScript (although I am fluent in about 50 other programming languages), I didn't take it too seriously until I started seeing what other Node projects (like apollo-client) were doing with it.

**Comment by grantcarthew** [comment]
That's great. Any contribution is appreciated. Thanks.

**Comment by grantcarthew** [comment]
[Pull Request Merged](https://github.com/grantcarthew/node-rethinkdb-job-queue/pull/66)

Published to npm with v3.1.2

Test out the published package @viridia and let me know if there are any issues.

Thanks for your contribution. Much appreciated.

**Comment by viridia** [comment]
I found a couple of errors - the cancelJob, removeJob, reanimateJob returns an array of strings, not objects. I'll send a new PR, although I wan to wait a bit to see if I find anything else.

**Comment by grantcarthew** [comment]
That's fine. I expected that.
