### ISSUE TITLE
Detach queue from database without processing all jobs before

### ISSUE THREAD

**Issue by ebekebe** [grantcarthew/node-rethinkdb-job-queue#57]
I have the following problem: I have several workers that fetch jobs from the database and process them. There are always new jobs coming in, so I cannot pause the queue, because there will always be new jobs and the pause promise will not resolve. I want to shut down the worker gracefully. Is there a way to do this?

**Comment by grantcarthew** [comment]
Yes, [Queue.stop](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue.stop) will do this for you. It will only stop the local Queue object, not the whole queue.

**Comment by ebekebe** [comment]
Thanks for making this clear.
