### ISSUE TITLE
q.stop() sometimes hangs (Uncaught, unspecified "error" event)

### ISSUE THREAD

**Issue by ebekebe** [grantcarthew/node-rethinkdb-job-queue#58]
I wrote some tests around the queue with ava and at some point I need to stop the queue and wait for it close the database connection. Sometimes, however, q.stop() never resolves the promise and the tests time out and report the following:

```es2017
{ Error: Uncaught, unspecified "error" event. ([...])
    at Queue.emit (events.js:164:17)
    at raiseQueueErrorInternal (/root/api-server/node_modules/rethinkdb-job-queue/dist/queue.js:78:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Queue.stop (/root/api-server/node_modules/rethinkdb-job-queue/dist/queue.js:245:15)
```

**Comment by grantcarthew** [comment]
The error event arguments caused an error here @ebekebe 

Version 3 of the project fixed the event error handling.

That's not to say your stop error is fixed though.

Please upgrade to v3.0.0 and report back with the error if it still exists.

**Comment by ebekebe** [comment]
Sorry, I didn't realize there was a v3.0.0, because there is no release tag on Github for that version.

Now it seems the error is gone and my tests don't hang anymore. Thanks!

**Comment by grantcarthew** [comment]
@ebekebe I've deleted the old release. Are you not using npm to install?

**Comment by ebekebe** [comment]
I do kind of. I use the npm registry with yarn, but when I'm debugging I head to Github to look for open issues and the latest releases. I did an update of all packages a couple of days ago, to see if issues get resolved. I guess it was unlucky timing since the v3 release is only a week old.

Anyway, you boosted my confidence in your module, by replying so quickly. So thanks again for your help and your awesome module of course.

**Comment by grantcarthew** [comment]
@ebekebe Good stuff. Thanks mate.
