### ISSUE TITLE
Blotted logs

### ISSUE THREAD

**Issue by sagivf** [grantcarthew/node-rethinkdb-job-queue#60]
I have a queue that has jobs with `repeatDelay` on each Job.
The logs don't get cleared which causes:
1) Increased DB size.
2) The process running the queue memory usage gradually goes up and up.

Any advice on how to handle this?

**Comment by grantcarthew** [comment]
The latest version (3.1.0) added a [limitJobLogs](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Options#queue-limitjoblogs-option) Queue option. Is this what you need Sagiv?

**Comment by sagivf** [comment]
Yes thanks man, thats awesome 👍 Are there any significant  breaking changes in 3.x? Is there a changelog for breaking changes?

**Comment by grantcarthew** [comment]
[Change Log](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Change-Log)

Are you using the error events? v3 changed the error event arguments to fix a bug.

**Comment by sagivf** [comment]
No, glad to see you are semver compliante though 👍 
Thanks @grantcarthew this solved my problem. It even truncted the logs without having to reinstate the jobs or anything. Great work as always!
