### ISSUE TITLE
Queue creates extra job

### ISSUE THREAD

**Issue by viridia** [grantcarthew/node-rethinkdb-job-queue#65]
My app has a GUI which displays the current list of jobs in progress; one thing I see that's kind of odd is that occasionally there's an extra Job object that I didn't create. This Job object has state 'created' (it was never in a queue), has no custom properties (unlike my other jobs) - but the Query.findJobs() method does return it with the list of other jobs. I don't think this is a bug in my code, because I only have one call to createJob() and it always puts in a bunch of extra properties (not to mention doing json-schema validation on them). If I delete this extra job and wait a few minutes, another similar job will appear.

This is only an issue because of the fact that I'm displaying the list of jobs to the user and don't want to confuse them. I could filter this one out but I'd like to understand what's going on.

**Comment by grantcarthew** [comment]
Is it the [State Document](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/State-Document)?

**Comment by viridia** [comment]
Ah, yes it is, I hadn't read that part. So basically I just need to exclude that when processing the results from Queue.findJobs().

**Comment by grantcarthew** [comment]
`Queue.findJob` exposes the standard RethinkDB filter features so it will return the State Document. I could add a filter to prevent the State Document from being returned. Not sure on this.

I could also extend the Queue object api to add a `Queue.getStateDocument` or something similar. It shouldn't be needed though. The document is just a side effect of the global distributed events.

I am planning on adding more to the state document though with the Rate Limiting feature as indicated in #61

**Comment by grantcarthew** [comment]
We done here? Any feedback or ideas?

**Comment by viridia** [comment]
Close it.
