### ISSUE TITLE
Possible reconnection?

### ISSUE THREAD

**Issue by zllovesuki** [grantcarthew/node-rethinkdb-job-queue#72]
Currently, I'm running my applications on Kubernetes with 5 RethinkDB instances. Each application has a sidecar RethinkDB proxy (so localhost). 

However, if for any reasons, the connection between the proxy and other instances is dropped, job queue doesn't seem to be aware of the issue, and nothing happens afterward.

Is it an issue on my end or something else?

**Comment by grantcarthew** [comment]
Hi Rachel. Not sure. You could supply your own rethinkdbdash connection object and test. The connections under the hood are all rethinkdbdash. Have a look at the options here: https://github.com/neumino/rethinkdbdash#importing-the-driver

**Comment by zllovesuki** [comment]
@grantcarthew Would you consider exposing `pingInterval` as an option? It seems like this is the option I was hoping for.

**Comment by zllovesuki** [comment]
Actually, I can work around this problem... Closing this issue now as it is not important.

**Comment by grantcarthew** [comment]
OK. Just for coverage, the `rethinkdbdash` driver is available at `Queue.r` and by the looks of the `rethinkdbdash` source, you can access the options by putting an underscore in front of them `r.prototype._pingInterval`.
