### ISSUE TITLE
Unhandled rejection RangeError: "port" option should be >= 0 and < 65536: 280161

### ISSUE THREAD

**Issue by chiragob** [grantcarthew/node-rethinkdb-job-queue#74]
Unhandled rejection RangeError: "port" option should be >= 0 and < 65536: 280161
    at lookupAndConnect (net.js:971:13)
    at Socket.connect (net.js:946:5)
    at Object.connect (net.js:76:35)
    at new Connection (/var/www/html/node/seneca-email/node_modules/rethinkdbdash/lib/connection.js:87:29)
    at /var/www/html/node/seneca-email/node_modules/rethinkdbdash/lib/index.js:82:5
    at Promise._execute (/var/www/html/node/seneca-email/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/var/www/html/node/seneca-email/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/www/html/node/seneca-email/node_modules/bluebird/js/release/promise.js:79:10)
    at Function.r.connect (/var/www/html/node/seneca-email/node_modules/rethinkdbdash/lib/index.js:81:11)
    at Pool.createConnection (/var/www/html/node/seneca-email/node_modules/rethinkdbdash/lib/pool.js:207:18)
    at Timeout._onTimeout (/var/www/html/node/seneca-email/node_modules/rethinkdbdash/lib/pool.js:58:16)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by grantcarthew** [comment]
Hi @chiragob,

Looks like you typed in a port number of 280161 and it needs to be under 65536.
See this document for port details: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Connection

**Comment by grantcarthew** [comment]
Incidentally one of the most important fault finding techniques you can learn is to take time and read the error messages.

**Comment by chiragob** [comment]
thanks for reply.
there is port number issue in option and we handle this issue using try catch but when addJob method is call it is crash my service. also queue.on error event also added but its not handle

**Comment by grantcarthew** [comment]
Can you show me the Queue instantiation code please @chiragob ?

**Comment by chiragob** [comment]
here is my code. we want override option base code so when anyone can override 
=========================job.js======================================
const Queue = require('rethinkdb-job-queue')

const defaultConnectionOptions = {
  host: 'localhost',
  port: 28015,
  db: 'jobQueue'
}

const defaultQueueOption = {
  name: 'SendEmail'
}

module.exports = function job (options) {
  options = this.util.deepextend({
    queueOption: defaultQueueOption,
    connctionOption: defaultConnectionOptions
  }, options)

  this.add('role:job,cmd:create', async function emailSend (msg, response) {
    let {err, result} = await createRethinkJobQueue(msg)
    if (err) {
      response(err)
    } else {
      response(null, result)
    }
  })

  let createRethinkJobQueue = async function (qdata) {
    try {
      let queueObj = await createJobQueue(options.connctionOption, options.queueOption)
      queueObj.on('error', (err) => { throw err })
      let job = await createJob(queueObj, { data: qdata })
      let savedJobs
      await addJob(queueObj, job)
        .then(result => {
          savedJobs = {'jobId': result[0].id}
        })
        .catch(err => { throw err })
      return {err: null, result: savedJobs}
    } catch (err) {
      return {err: customError(err), result: null}
    }
  }

  let createJobQueue = function (connctionOption, queueOption) {
    try {
      return new Queue(connctionOption, queueOption)
    } catch (err) {
      return (err)
    }
  }

  let createJob = async function (queueObj, QData) {
    try {
      return await queueObj.createJob({data: QData})
    } catch (err) {
      return (err)
    }
  }

  let addJob = async function (queueObj, job) {
    return new Promise(async (resolve, reject) => {
      try {
        await queueObj.addJob(job)
                      .catch(err => { throw err })
                      .then(result => resolve(result))
        // return added
      } catch (err) {
        reject(err)
      }
    })
  }
}

let customError = function (err, errorCode) {
  let errRes = {}
  errRes['error'] = {
    'message': err.message || 'Service not avaialble'
  }
  errRes['status'] = errorCode || 404
  return errRes
}
==========================server.js======================================
var seneca = require('seneca')

let connctionOption1 = {
	host: 'localhost',
  port: 280156,
  db: 'jobQueue'
}

seneca({tag:'job'})

	.use('job', {connctionOption:connctionOption1})
  //.use('mesh', {isbase: true, pin: 'role:job,cmd:create', timeout: 999999})
  .use('mesh', {
    isbase: true,
		timeout: 999999,
		listen: [
			{timeout: 999999, pin: 'role:job,cmd:create'}
		]
	})
  .ready(function(){
    console.log("job ready")
  })
=============================seneca-mesh.js=======================================
let senecaObj = require('seneca')

let bodyData = {
	"to":"abcd@mymail.com",
	"from":"info@mymail.com",
	"subject":"this is test mail",
	"body":"this is message body"
}

senecaObj()
	.use('mesh',{timeout: 999999})
	.act('role:job,cmd:create', bodyData, (err, done) => {
	if (err) {
		throw err
	}
	console.log('test-mesh done.', done)
})

**Comment by grantcarthew** [comment]
I can see the issue in your code above at this section here:

```js

let connctionOption1 = {
host: 'localhost',
port: 280156,
db: 'jobQueue'
}

```

The `port` property is being set to `280156` which is above the maximum port range available within the TCP specification. The TCP header has a port field that is 16 bit long allowing a maximum value of `65535`. You have set the port to greater than that value.

It looks like you made a typo from the default RethinkDB port of `28015` and accidentally added a `6` on the end of the port number. Or you decided to customize the port and exceeded the `65535` port range.

Change the `280156` number to one that is under `65535` and typically above `1024`.

Read more about port numbers here: https://en.wikipedia.org/wiki/Port_(computer_networking)

**Comment by chiragob** [comment]
thanks for review and resolved issue
but i try to handle this exception using try {} catch blocks but it is not handle, its crash server application.

**Comment by grantcarthew** [comment]
You made me have a look into this @chiragob and I you are right, you will not be able to catch the error because it is a constructor error. Have a read here for reference: https://stackoverflow.com/questions/5149619/what-should-a-javascript-constructor-return-if-it-fails

If you want to catch errors on the connection to RethinkDB my suggestion is to create the connection yourself and pass in the `rethinkdbdash` object once it has a successful connection. Here's the detail on passing a db driver rather than a connection object: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Constructor

**Comment by chiragob** [comment]
@grantcarthew thanks for suggestion. i tried rethinkdbdash but same issue. 
so i set one port check method before creating queue object like this. 

`checkPortNumber(options.connctionOption.port)
        .catch(err => { reject(err) })
        .then(async result => {....})`

`let checkPortNumber = function (port) {
  return new Promise(async (resolve, reject) => {
    if (port > 65535) {
      reject({error: {message: 'port number should be less then 65536'}})
    }
    resolve(true)
  })
}`
