### ISSUE TITLE
queue.process: how is dateEnable set when passing partially completed job to next

### ISSUE THREAD

**Issue by TomKaltz** [grantcarthew/node-rethinkdb-job-queue#79]
ref: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue.process#partly-completed-or-delayed-job

Seems like dateEnable is set to the future but I can't figure out how it is calculated.  Does it add the timeout value to current time?

**Comment by grantcarthew** [comment]
Hi Tom,
You have to set the dateEnable yourself.
No tricks to it.
If you want the job to run again as soon as you save it back to the queue, then don't change the dateEnable value.
If you want the job to be delayed, set the dateEnable value to a future date.

Hope that clears it up for you mate.
