### ISSUE TITLE
Job.addLog() should allow string as param

### ISSUE THREAD

**Issue by TomKaltz** [grantcarthew/node-rethinkdb-job-queue#8]
A Log object with sane defaults should be automatically created and added when passing a string to Job.addLog().

**Comment by grantcarthew** [comment]
Done. v0.4.0 supports Log objects, strings and other objects for the `Job.addLog` method call. If you pass a string or object it gets logged under a `log.data` property.

Thanks.

**Comment by TomKaltz** [comment]
Very nice!
