### ISSUE TITLE
How to halt currently running job in Jobqueue ?

### ISSUE THREAD

**Issue by gkumar9** [grantcarthew/node-rethinkdb-job-queue#80]
I am using jobqueue  for running some logic in backend. On certain event, I add entry to Jobqueue and job starts running (inside backend) and job status becomes 'Active'. Now what I need is, on another event from frontend, I need to stop this currently running job in jobqueue. I am using "CancelJob" method, but it only changes status to "Cancel", not halting currently running job from Jobqueue.

**Comment by grantcarthew** [comment]
Read through the [Queue.process](https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue.process) document page. You want to be using the `onCancel` parameter in the process handler.

**Comment by gkumar9** [comment]
Thanks, @grantcarthew ```onCancel``` worked and helped me abort my currently running process.

**Comment by grantcarthew** [comment]
Good stuff. Happy to help.
