### ISSUE TITLE
How to know if your worker is working or not ?

### ISSUE THREAD

**Issue by gkumar9** [grantcarthew/node-rethinkdb-job-queue#81]
Hello, I am looking for a method which could give me if my worker for jobqueue is currently running or not.
Here running doesn't mean if it's currently in  'active' state. I just mean if its just started or not.

Further,

If yes it's running then can I know at what position is the object is positioned? 

The idea came from gtmetrix, as it tells you where u at in joqueue.
Thank you. Been enjoying using this repo.

P.S
I did tried to find in  your wiki. But couldnt locate.

**Comment by grantcarthew** [comment]
Hi @gkumar9,

These questions are all answered in the documentation which is very extensive.
The wiki is up on the tabs and also on the home page of this repository.

The tabs at the top of this page are 'code', 'issues', 'pull req', 'projects', 'wiki' <= that's it.

The nav bar down the right hand side will help you get around the wiki.

Start at the top and work your way down.

To answer this question I think you are after this: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Job.updateProgress

Happy to help mate.
