### ISSUE TITLE
[bug] canceling a job while its active still makes the final status as "completed" rather than "cancelled".

### ISSUE THREAD

**Issue by gkumar9** [grantcarthew/node-rethinkdb-job-queue#82]
![screenshot from 2018-05-02 13-14-25](https://user-images.githubusercontent.com/33317261/39511362-d1b16cbe-4e0a-11e8-9999-6fd8d5393702.png)

**Comment by grantcarthew** [comment]
This could be either a race condition or mis-configuration @gkumar9 .
How many worker nodes do you have?
If you cancel the job on one worker node whilst the other node is just finishing the job, it would cause this issue.

**Comment by gkumar9** [comment]
I have only one worker @grantcarthew .
While listening to events I noticed that first **cancelled** is called and then **completed** event gets called.

**Comment by grantcarthew** [comment]
Sorry @gkumar9, I've been busy working on this: https://github.com/grantcarthew/node-perj
I'm not using RethinkDB at the moment so you are going to have to help with the debugging.
Is this a repeatable issue?

**Comment by gkumar9** [comment]
yes

**Comment by grantcarthew** [comment]
I'm happy to help you understand the code however I'm working on other projects right now. What tool do you want to use for casual chat? It used to be an easy choice. Not so much now. For instant messaging I use Signal however time zones can cause issues there. There's gitter, slack, etc.
