### ISSUE TITLE
delayed tasks not running

### ISSUE THREAD

**Issue by sagivf** [grantcarthew/node-rethinkdb-job-queue#83]
Hey @grantcarthew I know your not actively developing but I realy hope you can help me out on this issue.

I have a single node instance with single queues that have **delayed** tasks.
They seem not to be running even thought the `dateEnabled` has past and i'm not quite sure why.

First is seems like that without setting a `concurrency` level on the queue, the jobs didn't run unless there where not a part of the **masterInterval** review process.

After that it seems like only **jobs** that have a `highest` priority set are running...

Can you point me in the right direction as why delayed jobs would not run?

**Comment by grantcarthew** [comment]
What are the options your using @sagivf 

Ref: https://github.com/grantcarthew/node-rethinkdb-job-queue/wiki/Queue-Master#delayed-job-processing

**Comment by sagivf** [comment]
I saw that, yes, that is part of the issue, the queue isn't busy and the review isn't properly starting the jobs.

Basically there seem to be two problems:
1)
Originally the Queue properties where only 
```
{
 name: 'lesson_reminder',
masterInterval: 1000 * 20
}
```
and the jobs
```
 retryMax: 2,
 retryDelay: 200000,
 dateEnable,
name: `${lessonId}:reminder`,
data: {
  lessonId,
  type: reminderType,
  time: reminderTime
}
```

And although I saw the `state document`s timestamp was being updated, the jobs never started processing. Once I set the `concurrency` to 10 it started working. This happened locally to, so I can recreate it if you want.

2) After that I decided to set one job type `priority` to 'highest' and the rest to 'high' and while this worked locally, In production for some reason only the `highest` job was getting processed. This was pretty consistent. After I changed  all the jobs to `highest` everything was back to normal.

Any guesses?

**Comment by sagivf** [comment]
Unrelated, but how does debugging work? I  added DEBUG=true to the environment, but didn't see anything outputted to the console.

**Comment by grantcarthew** [comment]
The debug logs are written using this: https://www.npmjs.com/package/debug

I'm using [perj](https://github.com/grantcarthew/node-perj) for logging going forward but if I remember correctly you need to set the DEBUG env var to the module name you want to display logs for or `*`.

I don't even have RethinkDB or Docker installed at the moment @sagivf. If you are happy to debug it I'll help were I can.

I recon the [queue-process.js restart](https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/queue-process.js#L215) call is the place to start debugging. This gets called by [db-review.js](https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/src/db-review.js#L104).

**Comment by grantcarthew** [comment]
Do you use [Signal](https://signal.org/)?

**Comment by sagivf** [comment]
I installed it - is it safe?
I'll start with debugging what I was able to recreate locally with the concurrency level not being set.

**Comment by grantcarthew** [comment]
Send me an email with first name at last name dot net and I'll send you my phone number for Signal contact. Or send my your number.

**Comment by sagivf** [comment]
I send you an email.

I tried recreating my initial issue locally and now it's working...
I'll close the issue and will keep an eye out for the issue, since everything is time based it's kind of hard to recreate. Thanks, I'm slowly getting to know this project more and more, so I hope I can be more active soon...
