### ISSUE TITLE
Queue.addJob should be able to accept simple object

### ISSUE THREAD

**Issue by TomKaltz** [grantcarthew/node-rethinkdb-job-queue#9]
Similar to #8, addJob should be able to take a simple object and auto populate missing options with sane defaults before saving job to database.

**Comment by grantcarthew** [comment]
I copied a lot of the API from bull/kue/bee queue projects.
I didn't event think about doing something simple like this.
I'll work on it.

**Comment by grantcarthew** [comment]
As with #11, I'm going to leave this API as is.

Thanks.

**Comment by grantcarthew** [comment]
Edit:  Moving this comment here.

I decided not to change this API @TomKaltz.
I know it is not the cleanest API to ever exist however there are advantages.

### Pros

Can create jobs synchronously.
No database access until added to the queue.
Custom properties make the jobs very flexible.

### Cons

API is a little messy
I did consider an extra Queue method to create and add however it is moving away from keeping it simple again.

I might make minor changes to the API but the createJob and addJob will be separate.

Thanks again.

**Comment by grantcarthew** [comment]
So I am glad I have kept the `Queue.createJob` and `Queue.addJob` separate, this issue is an example of why I chose this path: https://github.com/OptimalBits/bull/issues/331

**Comment by TomKaltz** [comment]
Now that createJob is so versatile it's really not that big of a deal but IMHO addJob should still be able to handle situation where I just want to add a single job quickly by passing in minimal data.  It's merely for a small amount of extra convenience, though, so I rest my case.

Great library!
